package com.telefonica.incas.experimental.datafeed

//Please note, character 'c' is padded to the left of field name in case  1.Name starts with Number 2.Name of field is type
object enumSchemaBillshock extends Enumeration {
type enumSchemaBillshock = Value

    val recordtype                                 = Value(1-1)
    val localsequencenumber                        = Value(2-1)
    val servedimsi                                 = Value(3-1)
    val ggsnaddress                                = Value(4-1)
    val chargingid                                 = Value(5-1)
    val listofsgsnaddress                          = Value(6-1)
    val accesspointname                            = Value(7-1)
    val pdptype                                    = Value(8-1)
    val servedpdpaddress                           = Value(9-1)
    val remotepdpaddress                           = Value(10-1)
    val dynamicaddressflag                         = Value(11-1)
    val gosrequested                               = Value(12-1)
    val gosnegotiated                              = Value(13-1)
    val datavolumegprsuplink                       = Value(14-1)
    val datavolumegprsdownlink                     = Value(15-1)
    val changecondition                            = Value(16-1)
    val changetime                                 = Value(17-1)
    val recordopeningtime                          = Value(18-1)
    val duration                                   = Value(19-1)
    val causeforrecclosing                         = Value(20-1)
    val diagnostics                                = Value(21-1)
    val recordsequencenumber                       = Value(22-1)
    val nodeid                                     = Value(23-1)
    val packetvolumegprsuplink                     = Value(24-1)
    val packetvolumegprsdownlink                   = Value(25-1)
    val servedimei                                 = Value(26-1)
    val msclassmark                                = Value(27-1)
    val routingarea                                = Value(28-1)
    val locationarea                               = Value(29-1)
    val celldentity                                = Value(30-1)
    val sgsnchange                                 = Value(31-1)
    val apnselectionmode                           = Value(32-1)
    val accesspointnameoi                          = Value(33-1)
    val chargingcharacteristics                    = Value(34-1)
    val camelinformationpdd                        = Value(35-1)
    val systemtype                                 = Value(36-1)
    val rattype                                    = Value(37-1)
    val chchselectionmode                          = Value(38-1)
    val pmnidentifier                              = Value(39-1)
    val userlocationinformation                    = Value(40-1)
    val emsisdn                                    = Value(41-1)
    val dt                                         = Value(42-1)
    val hour                                       = Value(43-1)
    val csp                                        = Value(44-1)
}
