package com.telefonica.incas.experimental.datafeed

//Please note, character 'c' is padded to the left of field name in case  1.Name starts with Number 2.Name of field is type
object enumSchemaSignaling_sectors_stats_v1 extends Enumeration {
type enumSchemaSignaling_sectors_stats_v1 = Value

    val sectorid                                   = Value(1-1)
    val totevents                                  = Value(2-1)
    val totvalid                                   = Value(3-1)
    val totfailed                                  = Value(4-1)
    val activate_valid_2g                          = Value(5-1)
    val attach_valid_2g                            = Value(6-1)
    val deactivate_valid_2g                        = Value(7-1)
    val detach_valid_2g                            = Value(8-1)
    val israu_valid_2g                             = Value(9-1)
    val rau_valid_2g                               = Value(10-1)
    val service_request_valid_2g                   = Value(11-1)
    val others_valid_2g                            = Value(12-1)
    val activate_valid_3g                          = Value(13-1)
    val attach_valid_3g                            = Value(14-1)
    val deactivate_valid_3g                        = Value(15-1)
    val detach_valid_3g                            = Value(16-1)
    val israu_valid_3g                             = Value(17-1)
    val rau_valid_3g                               = Value(18-1)
    val service_request_valid_3g                   = Value(19-1)
    val others_valid_3g                            = Value(20-1)
    val l_attach_valid_4g                          = Value(21-1)
    val l_dedicated_bearer_activate_valid_4g       = Value(22-1)
    val l_dedicated_bearer_deactivate_valid_4g     = Value(23-1)
    val l_detach_valid_4g                          = Value(24-1)
    val l_handover_valid_4g                        = Value(25-1)
    val l_pdn_connect_valid_4g                     = Value(26-1)
    val l_pdn_disconnect_valid_4g                  = Value(27-1)
    val l_service_request_valid_4g                 = Value(28-1)
    val l_tau_valid_4g                             = Value(29-1)
    val others_valid_4g                            = Value(30-1)
    val activate_fail_2g                           = Value(31-1)
    val attach_fail_2g                             = Value(32-1)
    val deactivate_fail_2g                         = Value(33-1)
    val detach_fail_2g                             = Value(34-1)
    val israu_fail_2g                              = Value(35-1)
    val rau_fail_2g                                = Value(36-1)
    val service_request_fail_2g                    = Value(37-1)
    val others_fail_2g                             = Value(38-1)
    val activate_fail_3g                           = Value(39-1)
    val attach_fail_3g                             = Value(40-1)
    val deactivate_fail_3g                         = Value(41-1)
    val detach_fail_3g                             = Value(42-1)
    val israu_fail_3g                              = Value(43-1)
    val rau_fail_3g                                = Value(44-1)
    val service_request_fail_3g                    = Value(45-1)
    val others_fail_3g                             = Value(46-1)
    val l_attach_fail_4g                           = Value(47-1)
    val l_dedicated_bearer_activate_fail_4g        = Value(48-1)
    val l_dedicated_bearer_deactivate_fail_4g      = Value(49-1)
    val l_detach_fail_4g                           = Value(50-1)
    val l_handover_fail_4g                         = Value(51-1)
    val l_pdn_connect_fail_4g                      = Value(52-1)
    val l_pdn_disconnect_fail_4g                   = Value(53-1)
    val l_service_request_fail_4g                  = Value(54-1)
    val l_tau_fail_4g                              = Value(55-1)
    val others_fail_4g                             = Value(56-1)
    val dt                                         = Value(57-1)
    val hour                                       = Value(58-1)
}
