package com.telefonica.incas.experimental.datafeed

//Please note, character 'c' is padded to the left of field name in case  1.Name starts with Number 2.Name of field is type
object enumSchemaMobility_topk_v1 extends Enumeration {
type enumSchemaMobility_topk_v1 = Value

    val userid                                     = Value(1-1)
    val gyration                                   = Value(2-1)
    val bbdiagonal                                 = Value(3-1)
    val topduration                                = Value(4-1)
    val topkduration                               = Value(5-1)
    val sectorid1                                  = Value(6-1)
    val timesector1                                = Value(7-1)
    val sectorid2                                  = Value(8-1)
    val timesector2                                = Value(9-1)
    val sectorid3                                  = Value(10-1)
    val timesector3                                = Value(11-1)
    val sectorid4                                  = Value(12-1)
    val timesector4                                = Value(13-1)
    val sectorid5                                  = Value(14-1)
    val timesector5                                = Value(15-1)
    val sectorid6                                  = Value(16-1)
    val timesector6                                = Value(17-1)
    val sectorid7                                  = Value(18-1)
    val timesector7                                = Value(19-1)
    val sectorid8                                  = Value(20-1)
    val timesector8                                = Value(21-1)
    val sectorid9                                  = Value(22-1)
    val timesector9                                = Value(23-1)
    val sectorid10                                 = Value(24-1)
    val timesector10                               = Value(25-1)
    val sectorid11                                 = Value(26-1)
    val timesector11                               = Value(27-1)
    val sectorid12                                 = Value(28-1)
    val timesector12                               = Value(29-1)
    val sectorid13                                 = Value(30-1)
    val timesector13                               = Value(31-1)
    val sectorid14                                 = Value(32-1)
    val timesector14                               = Value(33-1)
    val sectorid15                                 = Value(34-1)
    val timesector15                               = Value(35-1)
    val sectorid16                                 = Value(36-1)
    val timesector16                               = Value(37-1)
    val sectorid17                                 = Value(38-1)
    val timesector17                               = Value(39-1)
    val sectorid18                                 = Value(40-1)
    val timesector18                               = Value(41-1)
    val sectorid19                                 = Value(42-1)
    val timesector19                               = Value(43-1)
    val sectorid20                                 = Value(44-1)
    val timesector20                               = Value(45-1)
    val dt                                         = Value(46-1)
    val hour                                       = Value(47-1)
}
