package com.telefonica.incas.experimental.datafeed

//Please note, character 'c' is padded to the left of field name in case  1.Name starts with Number 2.Name of field is type
object enumSchemaAscom1 extends Enumeration {
type enumSchemaAscom1 = Value

    val time                                       = Value(1-1)
    val latitude                                   = Value(2-1)
    val longitude                                  = Value(3-1)
    val dat                                        = Value(4-1)
    val equipment                                  = Value(5-1)
    val logfile                                    = Value(6-1)
    val operator                                   = Value(7-1)
    val region                                     = Value(8-1)
    val udr                                        = Value(9-1)
    val url                                        = Value(10-1)
    val technology                                 = Value(11-1)
    val status                                     = Value(12-1)
    val ctype                                      = Value(13-1)
    val technology_detail                          = Value(14-1)
    val duration_method_a                          = Value(15-1)
    val throughput_method_a                        = Value(16-1)
    val page_size                                  = Value(17-1)
    val sample_initiated_on_4g                     = Value(18-1)
    val city                                       = Value(19-1)
    val http_session_time                          = Value(20-1)
    val sample_initiated_on_3g                     = Value(21-1)
    val sample_initiated_on_2g                     = Value(22-1)
    val start_time                                 = Value(23-1)
    val reportstatus                               = Value(24-1)
    val route_type                                 = Value(25-1)
    val startlatitude                              = Value(26-1)
    val startlongitude                             = Value(27-1)
    val imei                                       = Value(28-1)
    val imsi                                       = Value(29-1)
    val channel                                    = Value(30-1)
    val technologylist                             = Value(31-1)
    val errorcause                                 = Value(32-1)
    val firstsignalstrength                        = Value(33-1)
    val lastsignalstrength                         = Value(34-1)
    val arithavgsignalstrength                     = Value(35-1)
    val logavgsignalstrength                       = Value(36-1)
    val route_part                                 = Value(37-1)
    val beacon_area                                = Value(38-1)
    val original_udr                               = Value(39-1)
    val callid                                     = Value(40-1)
    val trueregion                                 = Value(41-1)
    val notes                                      = Value(42-1)
    val reportperiod                               = Value(43-1)
    val currentset                                 = Value(44-1)
    val msisdn                                     = Value(45-1)
    val dt                                         = Value(46-1)
}
