package com.telefonica.incas.experimental.datafeed


import org.apache.spark.sql.types._

object DFSchemaSignaling_sectors_stats_v1 {

  val dFSchemaSignaling_sectors_stats_v1 = StructType(
    List(
      StructField("sectorid", StringType, nullable = true),
      StructField("totevents", IntegerType, nullable = true),
      StructField("totvalid", IntegerType, nullable = true),
      StructField("totfailed", IntegerType, nullable = true),
      StructField("activate_valid_2g", IntegerType, nullable = true),
      StructField("attach_valid_2g", IntegerType, nullable = true),
      StructField("deactivate_valid_2g", IntegerType, nullable = true),
      StructField("detach_valid_2g", IntegerType, nullable = true),
      StructField("israu_valid_2g", IntegerType, nullable = true),
      StructField("rau_valid_2g", IntegerType, nullable = true),
      StructField("service_request_valid_2g", IntegerType, nullable = true),
      StructField("others_valid_2g", IntegerType, nullable = true),
      StructField("activate_valid_3g", IntegerType, nullable = true),
      StructField("attach_valid_3g", IntegerType, nullable = true),
      StructField("deactivate_valid_3g", IntegerType, nullable = true),
      StructField("detach_valid_3g", IntegerType, nullable = true),
      StructField("israu_valid_3g", IntegerType, nullable = true),
      StructField("rau_valid_3g", IntegerType, nullable = true),
      StructField("service_request_valid_3g", IntegerType, nullable = true),
      StructField("others_valid_3g", IntegerType, nullable = true),
      StructField("l_attach_valid_4g", IntegerType, nullable = true),
      StructField("l_dedicated_bearer_activate_valid_4g", IntegerType, nullable = true),
      StructField("l_dedicated_bearer_deactivate_valid_4g", IntegerType, nullable = true),
      StructField("l_detach_valid_4g", IntegerType, nullable = true),
      StructField("l_handover_valid_4g", IntegerType, nullable = true),
      StructField("l_pdn_connect_valid_4g", IntegerType, nullable = true),
      StructField("l_pdn_disconnect_valid_4g", IntegerType, nullable = true),
      StructField("l_service_request_valid_4g", IntegerType, nullable = true),
      StructField("l_tau_valid_4g", IntegerType, nullable = true),
      StructField("others_valid_4g", IntegerType, nullable = true),
      StructField("activate_fail_2g", IntegerType, nullable = true),
      StructField("attach_fail_2g", IntegerType, nullable = true),
      StructField("deactivate_fail_2g", IntegerType, nullable = true),
      StructField("detach_fail_2g", IntegerType, nullable = true),
      StructField("israu_fail_2g", IntegerType, nullable = true),
      StructField("rau_fail_2g", IntegerType, nullable = true),
      StructField("service_request_fail_2g", IntegerType, nullable = true),
      StructField("others_fail_2g", IntegerType, nullable = true),
      StructField("activate_fail_3g", IntegerType, nullable = true),
      StructField("attach_fail_3g", IntegerType, nullable = true),
      StructField("deactivate_fail_3g", IntegerType, nullable = true),
      StructField("detach_fail_3g", IntegerType, nullable = true),
      StructField("israu_fail_3g", IntegerType, nullable = true),
      StructField("rau_fail_3g", IntegerType, nullable = true),
      StructField("service_request_fail_3g", IntegerType, nullable = true),
      StructField("others_fail_3g", IntegerType, nullable = true),
      StructField("l_attach_fail_4g", IntegerType, nullable = true),
      StructField("l_dedicated_bearer_activate_fail_4g", IntegerType, nullable = true),
      StructField("l_dedicated_bearer_deactivate_fail_4g", IntegerType, nullable = true),
      StructField("l_detach_fail_4g", IntegerType, nullable = true),
      StructField("l_handover_fail_4g", IntegerType, nullable = true),
      StructField("l_pdn_connect_fail_4g", IntegerType, nullable = true),
      StructField("l_pdn_disconnect_fail_4g", IntegerType, nullable = true),
      StructField("l_service_request_fail_4g", IntegerType, nullable = true),
      StructField("l_tau_fail_4g", IntegerType, nullable = true),
      StructField("others_fail_4g", IntegerType, nullable = true),
      StructField("dt", StringType, nullable = true),
      StructField("hour", StringType, nullable = true)
    ))
}
