package com.telefonica.incas.experimental.datafeed


import org.apache.spark.sql.types._

object DFSchemaMcdr {

  val dFSchemaMcdr = StructType(
    List(
      StructField("recordtype", StringType, nullable = true),
      StructField("servedimsi", StringType, nullable = true),
      StructField("gwaddress", StringType, nullable = true),
      StructField("chargingid", StringType, nullable = true),
      StructField("servingnodeaddress", StringType, nullable = true),
      StructField("accesspointnameni", StringType, nullable = true),
      StructField("pdppdntype", StringType, nullable = true),
      StructField("servedpdppdnaddress", StringType, nullable = true),
      StructField("dynamicaddressflag", StringType, nullable = true),
      StructField("recordopeningtime", StringType, nullable = true),
      StructField("duration", StringType, nullable = true),
      StructField("causeforrecclosing", StringType, nullable = true),
      StructField("recordsequencenumber", StringType, nullable = true),
      StructField("nodeid", StringType, nullable = true),
      StructField("localsequencenumber", StringType, nullable = true),
      StructField("apnselectionmode", StringType, nullable = true),
      StructField("servedmsisdn", StringType, nullable = true),
      StructField("chargingcharacteristics", StringType, nullable = true),
      StructField("chchselectionmode", StringType, nullable = true),
      StructField("servedimeisv", StringType, nullable = true),
      StructField("rattype", StringType, nullable = true),
      StructField("event_005_tac", StringType, nullable = true),
      StructField("event_005_eci", StringType, nullable = true),
      StructField("ratinggroup", StringType, nullable = true),
      StructField("resultcode", StringType, nullable = true),
      StructField("timeoffirstusage", StringType, nullable = true),
      StructField("timeoflastusage", StringType, nullable = true),
      StructField("timeusage", StringType, nullable = true),
      StructField("serviceconditionchange", StringType, nullable = true),
      StructField("qosinformationneg", StringType, nullable = true),
      StructField("datavolumefbcuplink", StringType, nullable = true),
      StructField("datavolumefbcdownlink", StringType, nullable = true),
      StructField("timeofreport", StringType, nullable = true),
      StructField("failurehandlingcontinue", StringType, nullable = true),
      StructField("serviceidentifier", StringType, nullable = true),
      StructField("servingnodetype", StringType, nullable = true),
      StructField("starttime", StringType, nullable = true),
      StructField("stoptime", StringType, nullable = true),
      StructField("pdnconnectionid", StringType, nullable = true),
      StructField("sgsnchange", StringType, nullable = true),
      StructField("remotepdpaddress", StringType, nullable = true),
      StructField("qosrequested", StringType, nullable = true),
      StructField("qosnegotiated", StringType, nullable = true),
      StructField("datavolumegprsuplink", StringType, nullable = true),
      StructField("datavolumegprsdownlink", StringType, nullable = true),
      StructField("changecondition", StringType, nullable = true),
      StructField("changetime", StringType, nullable = true),
      StructField("diagnostics", StringType, nullable = true),
      StructField("recordextensions", StringType, nullable = true),
      StructField("packetvolumegprsuplink", StringType, nullable = true),
      StructField("packetvolumegprsdownlink", StringType, nullable = true),
      StructField("msclassmark", StringType, nullable = true),
      StructField("routingarea", StringType, nullable = true),
      StructField("locationarea", StringType, nullable = true),
      StructField("cellidentity", StringType, nullable = true),
      StructField("accesspointnameoi", StringType, nullable = true),
      StructField("camelinformationpdp", StringType, nullable = true),
      StructField("systemtype", StringType, nullable = true),
      StructField("pmnidentifier", StringType, nullable = true),
      StructField("dt", StringType, nullable = true),
      StructField("hour", IntegerType, nullable = true),
      StructField("csp", StringType, nullable = true)
    ))
}
